Recommendation system
lastmart/FlowerApp pull request #2
Opened 2024-11-12 18:57 UTC by Greenbelg

2024-11-18 12:30 UTC, goodoldlameme commented on FlowerApp.Service/Services/IRecommendationService.cs
> +    Task<RecommendationResult> GetRecommendations(Guid? userId, string? name, int take, List<Answer> userAnswers);
take я бы сделала последним параметром

2024-11-18 12:31 UTC, goodoldlameme commented on FlowerApp.Service/Services/RecommendationService.cs
> +        if (userId == null)
метод огромный, нужно его декомпозировать

2024-11-18 12:32 UTC, goodoldlameme commented on FlowerApp.Service/Services/RecommendationService.cs
> +            errors.Add($"Invalid question IDs: {string.Join(", ", invalidQuestionIds)}");
как будто тут не нужен список с ошибками

2024-11-18 12:37 UTC, goodoldlameme commented on FlowerApp.Service/Services/RecommendationService.cs
> +            var question = await questionsStorage.Get(answer.QuestionId);
Если есть возможность - лучше бы сделать на вход пары вопрос-ответ, мы же все равно в момент получения ответов это знаем и можем систему сами проектировать

2024-11-18 12:39 UTC, goodoldlameme commented on FlowerApp.Service/Services/RecommendationService.cs
> +        var response = await httpClient.PostAsync("http://127.0.0.1:8000/recommendations", requestContent);
давайте это вынесем в отдельный клиент

2024-11-18 12:40 UTC, goodoldlameme requested changes
Жду правок

2024-12-09 17:51 UTC, Greenbelg commented on FlowerApp.Service/Services/RecommendationService.cs
> +            var question = await questionsStorage.Get(answer.QuestionId);
Но нам все равно придется ходить в базу, чтобы узнать всю модель вопроса. Кажется, оптимизации не получим

2024-12-10 12:49 UTC, goodoldlameme approved these changes

2024-12-22 07:10 UTC, merged