Trades
lastmart/FlowerApp pull request #3
Opened 2024-11-27 10:01 UTC by GlebMoskalev

2024-12-04 04:00 UTC, goodoldlameme requested changes
слои попутались

2024-12-04 04:00 UTC, goodoldlameme commented on FlowerApp.Data/Storages/TradeStorage.cs
> +        switch (includeUserTrades)
```
if  (!string.IsNullOrEmpty(userId))
{
    var userGuid = Guid.Parse(userId);
    query = query.Where(t => includeUserTrades ? t.UserIdentifier == userGuid : t.UserIdentifier != userGuid);
}
```

2024-12-04 04:00 UTC, goodoldlameme commented on FlowerApp.Domain/ApplicationModels/TradeModels/GetTradeResponse.cs
> +public record GetTradeResponse(int Count, IEnumerable<DbTrade> Trades);
Почему тут зависимость от модели из бд, если это доменная модель

2024-12-04 04:00 UTC, goodoldlameme commented on FlowerApp.Service/Controllers/TradesController.cs
> +            return StatusCode(500, "Internal server error");
тут можно использовать мидлвары обработки исключений

2024-12-04 04:00 UTC, goodoldlameme commented on FlowerApp.Service/Controllers/UsersController.cs
> +using ApplicationUser = FlowerApp.Domain.ApplicationModels.UserModels.User;
Тут вообще по идее хорошо бы сделать DTO модели, слоя 3 - интерфейсов, доменный и данных

2024-12-04 04:00 UTC, goodoldlameme commented on FlowerApp.Service/Services/ITradeService.cs
> +using DbTrade = FlowerApp.Domain.DbModels.Trade;
тоже не понимаю почему тут бд модель

2024-12-10 19:36 UTC, lastmart commented on FlowerApp.Data/Storages/TradeStorage.cs
> +        switch (includeUserTrades)
++

2024-12-10 21:26 UTC, Greenbelg commented
По ревью ещё не все: блок с юзерами пока не сделан, так как надо будет согласовать, что там куда летает (какие модели)

2024-12-25 06:29 UTC, goodoldlameme requested changes
Неожиданные ошибки это 500, а не 400

2024-12-25 06:29 UTC, goodoldlameme commented on FlowerApp.Service/Controllers/TradesController.cs
> +            return BadRequest("Failed to create trade");
BadRequest это только ошибки связанные с некорретными данными запроса, до этого было все правильно - люая неожиданная ошибка это 500

2024-12-25 08:47 UTC, merged